#ifndef AMH_CONFIG_H
#define AMH_CONFIG_H

// Generated by the AMH meta-harness from host/amh/usecases/ahrs/parameters.py.
// This checked-in copy holds the default values.
#define IMU_POLL_RATE_MS 20
#define FILTER_ALPHA     0.9600f

#endif // AMH_CONFIG_H
